### ISSUE TITLE
POOR README

### ISSUE THREAD

**Issue by unicodeveloper** [andela-vdugeri/Emoji#1]
This is a very poor readme. How do I use your API?. Where is the documentation for all the routes that exist and the kind of information that they return and the kind of status codes.

How do i know how to be authenticated to make a post request.

All those vital info is missing.

Please fix ASAP!

I discovered that the documentation is on the emoji index page, then you should state that in the readme and provide the link to the homepage

**Comment by andela-vdugeri** [comment]
Ok. On it.
