### ISSUE TITLE
EmojiController.php

### ISSUE THREAD

**Issue by unicodeveloper** [andela-vdugeri/Emoji#10]
I am really starting to doubt in your abilities. You used to take care of all of these before, now I just see so many things that are obviously wrong that you should have taken care of.

```php
$response   = $app->response();
$response->header("Content-type", "application/json");
```

This block of code was repeated in all the functions here. Why not abstract it into a function of its own and call it in all the other functions?

**Comment by andela-vdugeri** [comment]
Sorry about that. Added that as a hotfix and forgot to refactor
